- date: April 2016 - September 2020
  title: äº¬éƒ½å¤§å­¦
  content: |
    å·¥å­¦éƒ¨ é›»æ°—é›»å­å·¥å­¦ç§‘
  link: https://www.s-ee.t.kyoto-u.ac.jp/
  color: success

- date: September 2016
  title: ã‚¨ãƒ¬ã‚¯ãƒˆãƒ­ãƒ‹ã‚¯ã‚¹ã‚µãƒãƒ¼ã‚­ãƒ£ãƒ³ãƒ— TAè³
  content: |
    äº¬éƒ½å¤§å­¦å·¥å­¦éƒ¨é›»æ°—é›»å­å·¥å­¦ç§‘ä¸»å‚¬ã®ã‚µãƒãƒ¼ã‚­ãƒ£ãƒ³ãƒ—
    LEGO Mindstormsã‚’ä½¿ã£ãŸãƒ­ãƒœãƒƒãƒˆè£½ä½œ
  link: https://www.s-ee.t.kyoto-u.ac.jp/ja/summercamp
  color: info

- date: September 2018
  title: ã‚¨ãƒ¬ã‚¯ãƒˆãƒ­ãƒ‹ã‚¯ã‚¹ã‚µãƒãƒ¼ã‚­ãƒ£ãƒ³ãƒ— å„ªå‹
  content: |
    äº¬éƒ½å¤§å­¦å·¥å­¦éƒ¨é›»æ°—é›»å­å·¥å­¦ç§‘ä¸»å‚¬ã®ã‚µãƒãƒ¼ã‚­ãƒ£ãƒ³ãƒ—
    å€’ç«‹æŒ¯å­ã®è‡ªå‹•åˆ¶å¾¡ã‚³ãƒ³ãƒ†ã‚¹ãƒˆ
  link: https://www.s-ee.t.kyoto-u.ac.jp/ja/summercamp/inv-pendulum/2018-kuee-sc3/report
  color: info

- date: March 2019 - December 2019
  title: æ ªå¼ä¼šç¤¾ ã‚·ãƒ¼ãƒ»ã‚ªãƒ¼ãƒ»ã‚³ãƒ³ãƒ´ (ã‚¢ãƒ«ãƒã‚¤ãƒˆ)
  content: |
    Windows ã‚«ãƒ¼ãƒãƒ«ãƒ¢ãƒ¼ãƒ‰ãƒ‡ãƒã‚¤ã‚¹ãƒ‰ãƒ©ã‚¤ãƒé–‹ç™º
    Windows GUIã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³é–‹ç™º
  link: https://www.co-conv.jp/
  color: danger

- date: April 2019 - September 2020
  title: Computer Vision Laboratory
  content: |
    äº¬éƒ½å¤§å­¦ å·¥å­¦éƒ¨ é›»æ°—é›»å­å·¥å­¦ç§‘
  link: https://vision.ist.i.kyoto-u.ac.jp
  color: success

- date: August 2019
  title: ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ãƒ»ã‚­ãƒ£ãƒ³ãƒ—å…¨å›½å¤§ä¼š2019
  content: |
    ç‹¬ç«‹è¡Œæ”¿æ³•äººæƒ…å ±å‡¦ç†æ¨é€²æ©Ÿæ§‹
    ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ãƒ»ã‚­ãƒ£ãƒ³ãƒ—äº‹æ¥­ ãƒ¡ã‚¤ãƒ³ã‚¤ãƒ™ãƒ³ãƒˆ
  link: https://www.ipa.go.jp/jinzai/camp/2019/zenkoku2019_index.html
  color: warning

- date: December 2019 - December 2021
  title: Webã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ (å¥‘ç´„ç¤¾å“¡)
  content: |
    Webãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰é–‹ç™º
    DevOps
    ã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ãƒªãƒ³ã‚°ãƒãƒã‚¸ãƒ¡ãƒ³ãƒˆ
  link: "#experiences"
  color: danger

- date: January 2020 - December 2022
  title: CAMPHOR- ã‚³ã‚¢ãƒ¡ãƒ³ãƒãƒ¼
  content: |
    äº¬éƒ½ã®ITç³»å­¦ç”Ÿã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£CAMPHOR-ã®é‹å–¶
  link: https://camph.net/
  color: success

- date: August 2020
  title: ã‚¯ãƒƒã‚¯ãƒ‘ãƒƒãƒ‰æ ªå¼ä¼šç¤¾ (ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ³)
  content: |
    Webã‚¢ãƒ—ãƒªé–‹ç™º
    ã‚µãƒ¼ãƒ“ã‚¹é–‹ç™º
  link: https://info.cookpad.com/
  color: danger

- date: September 2020
  title: æ ªå¼ä¼šç¤¾ VOYAGE GROUP (ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ³)
  content: |
    ãƒãƒ¼ãƒ é–‹ç™º
    ãƒ•ãƒ«ã‚µã‚¤ã‚¯ãƒ«ãƒ‡ãƒ™ãƒ­ãƒƒãƒ‘ãƒ¼
  link: https://voyagegroup.com/
  color: danger

- date: October 2020 - September 2022
  title: Interactive Media Design Laboratory
  content: |
    å¥ˆè‰¯å…ˆç«¯ç§‘å­¦æŠ€è¡“å¤§å­¦é™¢å¤§å­¦
    å…ˆç«¯ç§‘å­¦æŠ€è¡“ç ”ç©¶ç§‘ æƒ…å ±ç§‘å­¦é ˜åŸŸ
  link: https://imdl.naist.jp/
  color: success

- date: August 2021
  title: ã‚µã‚¤ãƒœã‚¦ã‚ºæ ªå¼ä¼šç¤¾ (ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ³)
  content: |
    ç”Ÿç”£æ€§å‘ä¸Šãƒãƒ¼ãƒ 
    ã‚¤ãƒ³ãƒ•ãƒ©
  link: https://cybozu.co.jp/
  color: danger

- date: August 2021
  title: æ ªå¼ä¼šç¤¾ã¯ã¦ãª (ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ³)
  content: |
    ã‚·ã‚¹ãƒ†ãƒ ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒ éƒ¨
    SRE
  link: https://hatenacorp.jp/
  color: danger

- date: September 2021
  title: æ ªå¼ä¼šç¤¾ãƒŸã‚¯ã‚·ã‚£ (ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ³)
  content: |
    ãƒ©ã‚¤ãƒ–ã‚¨ã‚¯ã‚¹ãƒšãƒªã‚¨ãƒ³ã‚¹äº‹æ¥­æœ¬éƒ¨ ã‚·ã‚¹ãƒ†ãƒ éƒ¨ Fanstaé–‹ç™ºG
    Webãƒ•ãƒ­ãƒ³ãƒˆã‚¨ãƒ³ãƒ‰é–‹ç™º
    ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰é–‹ç™º
  link: https://www.mixi.co.jp
  color: danger

- date: October 2021 - November 2021
  title: æ ªå¼ä¼šç¤¾ãƒ“ã‚ºãƒªãƒ¼ãƒ (ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ³)
  content: |
    ãƒ“ã‚ºãƒªãƒ¼ãƒäº‹æ¥­éƒ¨ ãƒ—ãƒ­ãƒ€ã‚¯ãƒˆé–‹ç™ºéƒ¨ ã‚·ã‚¹ãƒ†ãƒ æ¨ªæ–­G
    ãƒãƒƒã‚¯ã‚¨ãƒ³ãƒ‰é–‹ç™º
  link: https://www.bizreach.co.jp
  color: danger

- date: March 2022
  title: æ ªå¼ä¼šç¤¾ãƒŸã‚¯ã‚·ã‚£ (ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ³)
  content: |
    é–‹ç™ºæœ¬éƒ¨ CTOå®¤
  link: https://www.mixi.co.jp
  color: danger

- date: April 2023 -
  title: "ğŸŒ¼"
  link: https://duckduckgo.com/?q=%E3%81%9F%E3%82%93%E3%81%BD%E3%81%BD
  color: success
